WITH ACTIVE_USER_JOBS (Q_JOB_NAME, CPU_TIME, RUN_PRIORITY) AS (SELECT JOB_NAME, CPU_TIME, RUN_PRIORITY FROM TABLE (QSYS2.ACTIVE_JOB_INFO('NO','','','')) x WHERE JOB_TYPE <> 'SYS' ) 

SELECT timestampdiff(4,char(current_timestamp - V_SQL_STMT_START_TIMESTAMP )) run_minutes,
'CALL QSYS2.CANCEL_SQL('''||Q_JOB_NAME||''');', CPU_TIME JOB_CPU_MS, RUN_PRIORITY, V_SQL_STATEMENT_TEXT, V_SQL_STMT_START_TIMESTAMP,
V_CLIENT_WRKSTNNAME, V_CLIENT_IP_ADDRESS, V_CLIENT_APPLNAME, V_CLIENT_PROGRAMID, V_CLIENT_USERID, V_QUERY_OPTIONS_LIB_NAME 
FROM ACTIVE_USER_JOBS, TABLE(QSYS2.GET_JOB_INFO(Q_JOB_NAME)) B 
WHERE V_SQL_STMT_STATUS = 'ACTIVE' and V_SQL_STMT_START_TIMESTAMP < current_timestamp - 15 minutes
  and v_sql_statement_text like 'INSERT INTO PL2202PWH%'
order by run_minutes desc;
